### ISSUE TITLE
`abs.py` -> `abc.py`

### ISSUE THREAD

**Issue by elenakrittik** [discatpy-dev/library#13]
**Describe the Bug**
`abs.py` file contains abstract base classes and should be named `abc.py`. "abs" usually means "absolute" and will likely confuse future contributors.

**Reproduction Steps**
`ls`

**Expected Behavior**
A clear and meaningful name for file

**Actual Behavior**
File name which will likely cause misunderstandings

**Traceback Error**
N/A

**System Information**
N/A

**Additional Context**
N/A

**Comment by EmmmaTech** [comment]
Good call! I don't really work on the main branch anymore, but I will incorporate this in the rewrite

**Comment by EmmmaTech** [comment]
I didn't realize this already, but this has already been fixed in the private repo I had for the rewrite for a little bit
Since I merged the two, this issue has been resolved
Here's the exact commit if you're curious: 9b065c600151cb98bd9f0e505af4ee823d8396c3
